### ISSUE TITLE
Import CV from Text File

### ISSUE THREAD

**Issue by boveus** [samvera/questioning_authority#164]
Hey folks,
We are using the QA gem in our Hyrax app and making use of the feature that allows us to store our controlled vocabularies in a PostgreSQL DB.  We wrote a little utility that parses a text file and saves a new CV and set of terms to the QA authorities tables: https://github.com/gsu-library/controlled_vocabulary_importer.

Would this be something that would fit into the vision of the QA gem?  If so, I would be happy to dedicate some time to working on getting some of this functionality into QA.

Thanks.

**Comment by elrayle** [comment]
@boveus Thanks so much for sharing this.  I am just about done with a revamp of the documentation for QA.  Much of the README is moving to the Wiki.  I added a link to your importer script in the page talking about [Creating a custom controlled vocabulary via a database](https://github.com/samvera/questioning_authority/wiki/Creating-a-custom-controlled-vocabulary-via-a-database) in the Prerequisites section.
