### ISSUE TITLE
api docs link in wiki

### ISSUE THREAD

**Issue by ConorSheehan1** [samvera/questioning_authority#176]
[The previous version](https://github.com/samvera/questioning_authority/wiki/Home/8bf8ef838bdbd983f033f86a8aaf9befe5e73541) of the Wiki had a couple of broken links, for example the [API Documentation link](https://www.rubydoc.info/github/projecthydra/questioning_authority/)

 The error message was:

Oops,
We Couldn't Find That GitHub Project
We haven't generated any docs for projecthydra/questioning_authority. 

I just edited them there to use samvera instead of project hydra and that seemed to do the trick. However, I was surprised I could edit the wiki without making a pr or something. 
Is the wiki mean to be publicly editable?

**Comment by elrayle** [comment]
@ConorSheehan1 Thanks for the heads up on this.  I'll take a look at it.

**Comment by elrayle** [comment]
Updates to the wiki are now limited to users with push access to QA.
