### ISSUE TITLE
enable functional index generator

### ISSUE THREAD

**Issue by ConorSheehan1** [samvera/questioning_authority#224]
Is it possible to enable the [add_index_to_local_authorities.rb](https://github.com/samvera/questioning_authority/blob/437630e46c989d5dec0f9c6a63f3898101349a99/lib/generators/qa/local/tables/templates/add_index_to_local_authorities.rb#L1) generator now?

As far as I can tell, qa depends on rails 5 since at least [v3.0.0](https://rubygems.org/gems/qa/versions/3.0.0), and [rails 5 supports functional indexes](https://github.com/rails/rails/commit/edc2b7718725016e988089b5fb6d6fb9d6e16882).

**Comment by elrayle** [comment]
@ConorSheehan1 Seems like this should be possible now.  Are you interested in submitting a PR that puts this in place?

**Comment by elrayle** [comment]
FYI... there are instructions for setting up the indexing manually in the [wiki documentation](https://github.com/samvera/questioning_authority/wiki/Creating-a-custom-controlled-vocabulary-via-a-database#adding-an-index).

**Comment by ConorSheehan1** [comment]
Yes I'm interested :) It's the end of the day where I am though, so I'll take a crack at it tomorrow morning when I'm back at my computer

**Comment by ConorSheehan1** [comment]
@elrayle I think I got this wrong, sorry.

Looks like the functional index support in rails 5 that I referenced is [for postgres only](https://github.com/rails/rails/commit/edc2b7718725016e988089b5fb6d6fb9d6e16882).
Functional indexes [for sqlite](https://github.com/rails/rails/pull/33874/commits/3a36cb08687aa337efca4dff12d20901d4d8029e) are added in rails 6.
Same thing for [mysql functional indexes](https://github.com/rails/rails/pull/34307/commits/a2ad8f456e29f760f78333e14474868a63a22a6f).

I started making the changes, but ran into an error where the schema contains a `nil` where it should have `'lower(label)'`

```ruby
class AddIndexToLocalAuthorities < ActiveRecord::Migration[5.2]
  def change
    add_index :qa_local_authority_entries,
                ['local_authority_id', 'lower(local_authority_entry_label)'],
                name: 'index_local_authority_entries_on_lower_label',
                unique: true
  end
end
```

generates an invalid schema

```ruby
  create_table "qa_local_authority_entries", force: :cascade do |t|
    t.integer "local_authority_id"
    t.string "label"
    t.string "uri"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    # on bundle exec rake db:migrate
    # rake aborted!
    # NoMethodError: undefined method `to_sym' for nil:NilClass
    t.index ["local_authority_id", nil], name: "index_local_authority_entries_on_lower_label", unique: true
  end
```
