### ISSUE TITLE
Release 0.6.0 breaks LoC functionality?

### ISSUE THREAD

**Issue by scande3** [samvera/questioning_authority#89]
Unsure of which exact change is causing this issue but having to version my code to use the 0.5.0 release to avoid the below. Perhaps there was an API change that isn't documented? (It doesn't look like the CHANGELOG was ever updated for the 0.6.0 release). 

In 0.5.0, doing:
`authority_check = Qa::Authorities::Loc.subauthority_for('relators')`
`authority_result = authority_check.search(URI.escape('Photographer'))`

**Returns:**
`[{"id"=>"info:lc/vocabulary/relators/pht", "label"=>"Photographer"}]`

Meanwhile, in 0.6.0, that same code of:
`authority_check = Qa::Authorities::Loc.subauthority_for('relators')`
`authority_result = authority_check.search(URI.escape('Photographer'))`

**Returns:**
`[{"id"=>"info:lc/vocabulary/relators/cst", "label"=>"Costume designer"}, {"id"=>"info:lc/vocabulary/relators/clr", "label"=>"Colorist"}, {"id"=>"info:lc/vocabulary/relators/scl", "label"=>"Sculptor"}, {"id"=>"info:lc/vocabulary/relators/prs", "label"=>"Production designer"}, {"id"=>"info:lc/vocabulary/relators/dis", "label"=>"Dissertant"}, {"id"=>"info:lc/vocabulary/relators/arr", "label"=>"Arranger"}, {"id"=>"info:lc/vocabulary/relators/wdc", "label"=>"Woodcutter"}, {"id"=>"info:lc/vocabulary/relators/cre", "label"=>"Creator"}, {"id"=>"info:lc/vocabulary/relators/act", "label"=>"Actor"}, {"id"=>"info:lc/vocabulary/relators/cas", "label"=>"Caster"}, {"id"=>"info:lc/vocabulary/relators/pop", "label"=>"Printer of plates"}, {"id"=>"info:lc/vocabulary/relators/res", "label"=>"Researcher"}, {"id"=>"info:lc/vocabulary/relators/len", "label"=>"Lender"}, {"id"=>"info:lc/vocabulary/relators/clt", "label"=>"Collotyper"}, {"id"=>"info:lc/vocabulary/relators/rpt", "label"=>"Reporter"}, {"id"=>"info:lc/vocabulary/relators/elg", "label"=>"Electrician"}, {"id"=>"info:lc/vocabulary/relators/mdc", "label"=>"Metadata contact"}, {"id"=>"info:lc/vocabulary/relators/rdd", "label"=>"Radio director"}, {"id"=>"info:lc/vocabulary/relators/bnd", "label"=>"Binder"}, {"id"=>"info:lc/vocabulary/relators/art", "label"=>"Artist"}] 
`

Of note, while I get a response, there is no "Photographer" role returned.

Any help would be appreciated as to why the above code works differently in 0.5.0 compared to 0.6.0. Thanks!

**Comment by jcoyne** [comment]
I'm not seeing anything that stands out in the diff: 
https://github.com/projecthydra-labs/questioning_authority/compare/v0.5.0...v0.6.0

**Comment by elrayle** [comment]
For latest version of QA...

    http://localhost:3000/qa/search/loc/relators?q=Photographer

Returns...

    [{"id":"info:lc/vocabulary/relators/pht","label":"Photographer"}]

This matches the results of the original query reported in this issue, so I assume the issue no longer applies.
