### ISSUE TITLE
Replace :label with :pref_label

### ISSUE THREAD

**Issue by barmintor** [samvera/questioning_authority#99]
To ease incorporation of linked data sources and accommodate potentially multiple labels, make :id anf :pref_label the single-value required keys in the results hash

**Comment by elrayle** [comment]
@barmintor This issue has been open a long while.  And much work has gone into making QA work with linked data.  I am closing this issue.  You may want to review the [linked data documentation](https://github.com/samvera/questioning_authority/wiki/Using-the-Linked-Data-module-to-access-authorities).  If you continue to have questions or suggestions, please enter a new issue.
